// ... existing code up to line 81 ...
file.WriteLine "        }" // end of invoke block
// Insert combined abilities definitions
file.WriteLine ""
file.WriteLine "        // Combined abilities for ARTEMAN"
file.WriteLine ""
// arti_arti_arti
file.WriteLine "        \"arteman_arti_arti_arti\""
file.WriteLine "        {"
file.WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
file.WriteLine "            \"AbilityTextureName\"            \"invoker_quas\""
file.WriteLine "            \"MaxLevel\"                        \"1\""
file.WriteLine "            \"AbilityCooldown\"                \"0\""
file.WriteLine "            \"AbilityManaCost\"                \"0\""
file.WriteLine "            \"OnSpellStart\""
file.WriteLine "            {"
file.WriteLine "                \"RunScript\""
file.WriteLine "                {"
file.WriteLine "                    \"ScriptFile\"            \"abilities/combined_arti_arti_arti.lua\""
file.WriteLine "                    \"Function\"                \"arteman_arti_arti_arti\""
file.WriteLine "                }"
file.WriteLine "            }"
        file.WriteLine "        }" // end of invoke block
        // Insert combined abilities definitions
        file.WriteLine ""
        file.WriteLine "        // Combined abilities for ARTEMAN"
        file.WriteLine ""
        // arti_arti_arti
        file.WriteLine "        \"arteman_arti_arti_arti\""
        file.WriteLine "        {"
        file.WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
        file.WriteLine "            \"AbilityTextureName\"            \"invoker_quas\""
        file.WriteLine "            \"MaxLevel\"                        \"1\""
        file.WriteLine "            \"AbilityCooldown\"                \"0\""
        file.WriteLine "            \"AbilityManaCost\"                \"0\""
        file.WriteLine "            \"OnSpellStart\""
        file.WriteLine "            {"
        file.WriteLine "                \"RunScript\""
        file.WriteLine "                {"
        file.WriteLine "                    \"ScriptFile\"            \"abilities/combined_arti_arti_arti.lua\""
        file.WriteLine "                    \"Function\"                \"arteman_arti_arti_arti\""
        file WriteLine "                }"
        file.WriteLine "            }"
        file WriteLine "        }"
        file WriteLine ""
        // mont_mont_mont
        file.WriteLine "        \"arteman_mont_mont_mont\""
        file WriteLine "        {"
        file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
        file WriteLine "            \"AbilityTextureName\"            \"invoker_exort\""
        file WriteLine "            \"MaxLevel\"                        \"1\""
        file WriteLine "            \"AbilityCooldown\"                \"0\""
        file WriteLine "            \"AbilityManaCost\"                \"0\""
        file WriteLine "            \"OnSpellStart\""
        file WriteLine "            {"
        file WriteLine "                \"RunScript\""
        file WriteLine "                {"
        file WriteLine "                    \"ScriptFile\"            \"abilities/combined_mont_mont_mont.lua\""
        file WriteLine "                    \"Function\"                \"arteman_mont_mont_mont\""
        file WriteLine "                }"
        file WriteLine "            }"
        file WriteLine "        }"
        file WriteLine ""
        // pira_pira_pira
        file WriteLine "        \"arteman_pira_pira_pira\""
        file WriteLine "        {"
        file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
        file WriteLine "            \"AbilityTextureName\"            \"invoker_wex\""
        file WriteLine "            \"MaxLevel\"                        \"1\""
        file WriteLine "            \"AbilityCooldown\"                \"0\""
        file WriteLine "            \"AbilityManaCost\"                \"0\""
        file WriteLine "            \"OnSpellStart\""
        file WriteLine "            {"
        file WriteLine "                \"RunScript\""
        file WriteLine "                {"
        file WriteLine "                    \"ScriptFile\"            \"abilities/combined_pira_pira_pira.lua\""
        file WriteLine "                    \"Function\"                \"arteman_pira_pira_pira\""
        file WriteLine "                }"
        file WriteLine "            }"
        file WriteLine "        }"
        file WriteLine ""
        // arti_mont_pira
        file WriteLine "        \"arteman_arti_mont_pira\""
        file WriteLine "        {"
        file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
        file WriteLine "            \"AbilityTextureName\"            \"invoker_quas\""
        file WriteLine "            \"MaxLevel\"                        \"1\""
        file WriteLine "            \"AbilityCooldown\"                \"0\""
        file WriteLine "            \"AbilityManaCost\"                \"0\""
        file WriteLine "            \"OnSpellStart\""
        file WriteLine "            {"
        file WriteLine "                \"RunScript\""
        file WriteLine "                {"
        file WriteLine "                    \"ScriptFile\"            \"abilities/combined_arti_mont_pira.lua\""
        file WriteLine "                    \"Function\"                \"arteman_arti_mont_pira\""
        file WriteLine "                }"
        file WriteLine "            }"
        file WriteLine "        }"
        file WriteLine ""
        // arti_arti_mont
        file WriteLine "        \"arteman_arti_arti_mont\""
        file WriteLine "        {"
        file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
        file WriteLine "            \"AbilityTextureName\"            \"invoker_quas\""
        file WriteLine "            \"MaxLevel\"                        \"1\""
        file WriteLine "            \"AbilityCooldown\"                \"0\""
        file WriteLine "            \"AbilityManaCost\"                \"0\""
        file WriteLine "            \"OnSpellStart\""
        file WriteLine "            {"
        file WriteLine "                \"RunScript\""
        file WriteLine "                {"
        file WriteLine "                    \"ScriptFile\"            \"abilities/combined_arti_arti_mont.lua\""
        file WriteLine "                    \"Function\"                \"arteman_arti_arti_mont\""
        file WriteLine "                }"
        file WriteLine "            }"
        file WriteLine "        }"
        file WriteLine ""
        // arti_arti_pira
        file WriteLine "        \"arteman_arti_arti_pira\""
        file WriteLine "        {"
        file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
        file WriteLine "            \"AbilityTextureName\"            \"invoker_quas\""
        file WriteLine "            \"MaxLevel\"                        \"1\""
        file WriteLine "            \"AbilityCooldown\"                \"0\""
        file WriteLine "            \"AbilityManaCost\"                \"0\""
        file WriteLine "            \"OnSpellStart\""
        file WriteLine "            {"
        file WriteLine "                \"RunScript\""
        file WriteLine "                {"
        file WriteLine "                    \"ScriptFile\"            \"abilities/combined_arti_arti_pira.lua\""
        file WriteLine "                    \"Function\"                \"arteman_arti_arti_pira\""
        file WriteLine "                }"
        file WriteLine "            }"
        file WriteLine "        }"
        file WriteLine ""
        // arti_mont_mont
        file WriteLine "        \"arteman_arti_mont_mont\""
        file WriteLine "        {"
        file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
        file WriteLine "            \"AbilityTextureName\"            \"invoker_quas\""
        file WriteLine "            \"MaxLevel\"                        \"1\""
        file WriteLine "            \"AbilityCooldown\"                \"0\""
        file WriteLine "            \"AbilityManaCost\"                \"0\""
        file WriteLine "            \"OnSpellStart\""
        file WriteLine "            {"
        file WriteLine "                \"RunScript\""
        file WriteLine "                {"
        file WriteLine "                    \"ScriptFile\"            \"abilities/combined_arti_mont_mont.lua\""
        file WriteLine "                    \"Function\"                \"arteman_arti_mont_mont\""
        file WriteLine "                }"
        file WriteLine "            }"
        file WriteLine "        }"
        file WriteLine ""
        // arti_pira_pira
        file WriteLine "        \"arteman_arti_pira_pira\""
        file WriteLine "        {"
        file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
        file WriteLine "            \"AbilityTextureName\"            \"invoker_quas\""
        file WriteLine "            \"MaxLevel\"                        \"1\""
        file WriteLine "            \"AbilityCooldown\"                \"0\""
        file WriteLine "            \"AbilityManaCost\"                \"0\""
        file WriteLine "            \"OnSpellStart\""
        file WriteLine "            {"
        file WriteLine "                \"RunScript\""
        file WriteLine "                {"
        file WriteLine "                    \"ScriptFile\"            \"abilities/combined_arti_pira_pira.lua\""
        file WriteLine "                    \"Function\"                \"arteman_arti_pira_pira\""
        file WriteLine "                }"
        file WriteLine "            }"
        file WriteLine "        }"
        file WriteLine ""
        // mont_mont_pira
        file WriteLine "        \"arteman_mont_mont_pira\""
        file WriteLine "        {"
        file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
        file WriteLine "            \"AbilityTextureName\"            \"invoker_exort\""
        file WriteLine "            \"MaxLevel\"                        \"1\""
        file WriteLine "            \"AbilityCooldown\"                \"0\""
        file WriteLine "            \"AbilityManaCost\"                \"0\""
        file WriteLine "            \"OnSpellStart\""
        file WriteLine "            {"
        file WriteLine "                \"RunScript\""
        file WriteLine "                {"
        file WriteLine "                    \"ScriptFile\"            \"abilities/combined_mont_mont_pira.lua\""
        file WriteLine "                    \"Function\"                \"arteman_mont_mont_pira\""
        file WriteLine "                }"
        file WriteLine "            }"
        file WriteLine "        }"
        file WriteLine ""
        // mont_pira_pira
        file WriteLine "        \"arteman_mont_pira_pira\""
        file WriteLine "        {"
        file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
        file WriteLine "            \"AbilityTextureName\"            \"invoker_exort\""
        file WriteLine "            \"MaxLevel\"                        \"1\""
        file WriteLine "            \"AbilityCooldown\"                \"0\""
        file WriteLine "            \"AbilityManaCost\"                \"0\""
        file WriteLine "            \"OnSpellStart\""
        file WriteLine "            {"
        file WriteLine "                \"RunScript\""
        file WriteLine "                {"
        file WriteLine "                    \"ScriptFile\"            \"abilities/combined_mont_pira_pira.lua\""
        file WriteLine "                    \"Function\"                \"arteman_mont_pira_pira\""
        file WriteLine "                }"
        file WriteLine "            }"
        file WriteLine "        }"
file.WriteLine ""
// mont_mont_mont
file.WriteLine "        \"arteman_mont_mont_mont\""
file.WriteLine "        {"
file.WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
file.WriteLine "            \"AbilityTextureName\"            \"invoker_exort\""
file.WriteLine "            \"MaxLevel\"                        \"1\""
file.WriteLine "            \"AbilityCooldown\"                \"0\""
file.WriteLine "            \"AbilityManaCost\"                \"0\""
file.WriteLine "            \"OnSpellStart\""
file.WriteLine "            {"
file.WriteLine "                \"RunScript\""
file.WriteLine "                {"
file WriteLine "                    \"ScriptFile\"            \"abilities/combined_mont_mont_mont.lua\""
file.WriteLine "                    \"Function\"                \"arteman_mont_mont_mont\""
file.WriteLine "                }"
file.WriteLine "            }"
file.WriteLine "        }"
file.WriteLine ""
// pira_pira_pira
file.WriteLine "        \"arteman_pira_pira_pira\""
file.WriteLine "        {"
file.WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
file.WriteLine "            \"AbilityTextureName\"            \"invoker_wex\""
file.WriteLine "            \"MaxLevel\"                        \"1\""
file.WriteLine "            \"AbilityCooldown\"                \"0\""
file.WriteLine "            \"AbilityManaCost\"                \"0\""
file.WriteLine "            \"OnSpellStart\""
file.WriteLine "            {"
file.WriteLine "                \"RunScript\""
file.WriteLine "                {"
file.WriteLine "                    \"ScriptFile\"            \"abilities/combined_pira_pira_pira.lua\""
file.WriteLine "                    \"Function\"                \"arteman_pira_pira_pira\""
file.WriteLine "                }"
file.WriteLine "            }"
file.WriteLine "        }"
file.WriteLine ""
// arti_mont_pira
file.WriteLine "        \"arteman_arti_mont_pira\""
file.WriteLine "        {"
file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
file.WriteLine "            \"AbilityTextureName\"            \"invoker_quas\""
file.WriteLine "            \"MaxLevel\"                        \"1\""
file.WriteLine "            \"AbilityCooldown\"                \"0\""
file.WriteLine "            \"AbilityManaCost\"                \"0\""
file.WriteLine "            \"OnSpellStart\""
file WriteLine "            {"
file WriteLine "                \"RunScript\""
file WriteLine "                {"
file WriteLine "                    \"ScriptFile\"            \"abilities/combined_arti_mont_pira.lua\""
file WriteLine "                    \"Function\"                \"arteman_arti_mont_pira\""
file WriteLine "                }"
file WriteLine "            }"
file WriteLine "        }"
file WriteLine ""
// arti_arti_mont
file WriteLine "        \"arteman_arti_arti_mont\""
file WriteLine "        {"
file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
file WriteLine "            \"AbilityTextureName\"            \"invoker_quas\""
file WriteLine "            \"MaxLevel\"                        \"1\""
file WriteLine "            \"AbilityCooldown\"                \"0\""
file WriteLine "            \"AbilityManaCost\"                \"0\""
file WriteLine "            \"OnSpellStart\""
file WriteLine "            {"
file WriteLine "                \"RunScript\""
file WriteLine "                {"
file WriteLine "                    \"ScriptFile\"            \"abilities/combined_arti_arti_mont.lua\""
file WriteLine "                    \"Function\"                \"arteman_arti_arti_mont\""
file WriteLine "                }"
file WriteLine "            }"
file WriteLine "        }"
file WriteLine ""
// arti_arti_pira
file WriteLine "        \"arteman_arti_arti_pira\""
file WriteLine "        {"
file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
file WriteLine "            \"AbilityTextureName\"            \"invoker_quas\""
file WriteLine "            \"MaxLevel\"                        \"1\""
file WriteLine "            \"AbilityCooldown\"                \"0\""
file WriteLine "            \"AbilityManaCost\"                \"0\""
file WriteLine "            \"OnSpellStart\""
file WriteLine "            {"
file WriteLine "                \"RunScript\""
file WriteLine "                {"
file WriteLine "                    \"ScriptFile\"            \"abilities/combined_arti_arti_pira.lua\""
file WriteLine "                    \"Function\"                \"arteman_arti_arti_pira\""
file WriteLine "                }"
file WriteLine "            }"
file WriteLine "        }"
file WriteLine ""
// arti_mont_mont
file WriteLine "        \"arteman_arti_mont_mont\""
file WriteLine "        {"
file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
file WriteLine "            \"AbilityTextureName\"            \"invoker_quas\""
file WriteLine "            \"MaxLevel\"                        \"1\""
file WriteLine "            \"AbilityCooldown\"                \"0\""
file WriteLine "            \"AbilityManaCost\"                \"0\""
file WriteLine "            \"OnSpellStart\""
file WriteLine "            {"
file WriteLine "                \"RunScript\""
file WriteLine "                {"
file WriteLine "                    \"ScriptFile\"            \"abilities/combined_arti_mont_mont.lua\""
file WriteLine "                    \"Function\"                \"arteman_arti_mont_mont\""
file WriteLine "                }"
file WriteLine "            }"
file WriteLine "        }"
file WriteLine ""
// arti_pira_pira
file WriteLine "        \"arteman_arti_pira_pira\""
file WriteLine "        {"
file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
file WriteLine "            \"AbilityTextureName\"            \"invoker_quas\""
file WriteLine "            \"MaxLevel\"                        \"1\""
file WriteLine "            \"AbilityCooldown\"                \"0\""
file WriteLine "            \"AbilityManaCost\"                \"0\""
file WriteLine "            \"OnSpellStart\""
file WriteLine "            {"
file WriteLine "                \"RunScript\""
file WriteLine "                {"
file WriteLine "                    \"ScriptFile\"            \"abilities/combined_arti_pira_pira.lua\""
file WriteLine "                    \"Function\"                \"arteman_arti_pira_pira\""
file WriteLine "                }"
file WriteLine "            }"
file WriteLine "        }"
file WriteLine ""
// mont_mont_pira
file WriteLine "        \"arteman_mont_mont_pira\""
file WriteLine "        {"
file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
file WriteLine "            \"AbilityTextureName\"            \"invoker_exort\""
file WriteLine "            \"MaxLevel\"                        \"1\""
file WriteLine "            \"AbilityCooldown\"                \"0\""
file WriteLine "            \"AbilityManaCost\"                \"0\""
file WriteLine "            \"OnSpellStart\""
file WriteLine "            {"
file WriteLine "                \"RunScript\""
file WriteLine "                {"
file WriteLine "                    \"ScriptFile\"            \"abilities/combined_mont_mont_pira.lua\""
file WriteLine "                    \"Function\"                \"arteman_mont_mont_pira\""
file WriteLine "                }"
file WriteLine "            }"
file WriteLine "        }"
file WriteLine ""
// mont_pira_pira
file WriteLine "        \"arteman_mont_pira_pira\""
file WriteLine "        {"
file WriteLine "            \"AbilityBehavior\"                \"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE\""
file WriteLine "            \"AbilityTextureName\"            \"invoker_exort\""
file WriteLine "            \"MaxLevel\"                        \"1\""
file WriteLine "            \"AbilityCooldown\"                \"0\""
file WriteLine "            \"AbilityManaCost\"                \"0\""
file WriteLine "            \"OnSpellStart\""
file WriteLine "            {"
file WriteLine "                \"RunScript\""
file WriteLine "                {"
file WriteLine "                    \"ScriptFile\"            \"abilities/combined_mont_pira_pira.lua\""
file WriteLine "                    \"Function\"                \"arteman_mont_pira_pira\""
file WriteLine "                }"
file WriteLine "            }"
file WriteLine "        }"
// ... existing code ...
