$s=[System.Collections.Generic.List[string]]::new() 
$s.Add('"DOTAAbilities"') 
$s.Add('{') 
$s.Add('    "Version"        "1"') 
$s.Add('    "arteman_letter_arti"') 
$s.Add('    {') 
$s.Add('        "AbilityBehavior"                "DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"') 
$s.Add('        "AbilityTextureName"            "invoker_quas"') 
$s.Add('        "MaxLevel"                        "1"') 
$s.Add('        "AbilityCooldown"                "0"') 
$s.Add('        "AbilityManaCost"                "0"') 
$s.Add('        "OnSpellStart"') 
$s.Add('        {') 
$s.Add('            "RunScript"') 
$s.Add('            {') 
$s.Add('                "ScriptFile"            "abilities/letter_arti.lua"') 
$s.Add('                "Function"                "arteman_letter_arti"') 
$s.Add('            }') 
$s.Add('        }') 
$s.Add('    }') 
$s.Add('    "arteman_letter_mont"') 
$s.Add('    {') 
$s.Add('        "AbilityBehavior"                "DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"') 
$s.Add('        "AbilityTextureName"            "invoker_exort"') 
$s.Add('        "MaxLevel"                        "1"') 
$s.Add('        "AbilityCooldown"                "0"') 
$s.Add('        "AbilityManaCost"                "0"') 
$s.Add('        "OnSpellStart"') 
$s.Add('        {') 
$s.Add('            "RunScript"') 
$s.Add('            {') 
$s.Add('                "ScriptFile"            "abilities/letter_mont.lua"') 
$s.Add('                "Function"                "arteman_letter_mont"') 
$s.Add('            }') 
$s.Add('        }') 
